### ISSUE TITLE
Project Gutenberg has blocked access for german users

### ISSUE THREAD

**Issue by Anonyfox** [dakra/speed-type#16]
^see the title "Project Gutenberg has blocked access for german users" - the package does not work here, except one uses workarounds like an US vpn service. Maybe a different text corpus can be used in such cases?

**Comment by parkouss** [comment]
yeah, that would be nice - do you know something like that? Note there speed-type-buffer and speed-type-region that you can use on custom local corpus.

**Comment by dakra** [comment]
Seems like Project Gutenberg allows German users again.

Closing for now. Please reopen if you still have problems.
Also #28 should make error messages for failed downloads nicer.
