### ISSUE TITLE
Add trigrams practicing method support

### ISSUE THREAD

**Issue by CorentinCAM** [dakra/speed-type#23]
I like the [trigram](http://tazzon.free.fr/dactylotest/tridactyl/) method to practice my typing.

Could it be possible to add the same kind of exercise to this package?

**Comment by texaco** [comment]
Hi!!

Since you can chose a region to practice, you have the text that you want.

**Comment by dakra** [comment]
@CorentinCAM do you have something specific in mind?
As @texaco if you have the text you can chose a region to practice.
Or maybe something like filtering the wordlist for only 3 character words and only display them?

**Comment by dakra** [comment]
As this is a rather old issue I'm closing it for now.
But please feel free to re-open it when you want to discuss anything more.
