### ISSUE TITLE
Feature: teach Emacs and Evil mode bindings.

### ISSUE THREAD

**Issue by holtzermann17** [dakra/speed-type#26]
Just tried speed-type for the first time, doing around 75WPM on the standard text examples. I wonder if the code could be pushed in the direction of something a bit like the [Emacs Evil Tutor](https://github.com/syl20bnr/evil-tutor), or [Vim Adventures](https://vim-adventures.com/)... so that we get hints and instructions on how to navigate through the text, and how to correct it, or how to use various other keybindings?  Here is an examples from Emacs Evil Tutor:

https://github.com/syl20bnr/evil-tutor/blob/master/tutor.txt#L93-L108

Granted, this is a bit of a stretch from what speed-type currently does, but maybe this is the best place to get an interactive tutor for Evil mode (or, similarly for Emacs bindings for those who know Vi).

**Comment by dakra** [comment]
I think something like `M-x help-with-tutorial` is out of scope for speed-type.
Especially if it's about learning Emacs (or evil) keybinding.
I think if we add a tutor like facility it probably should be about touch typing.

I would have a look at a PR that implements it but for now I close this as I
don't think I'm going to implement it.

Feel free to reopen or reply to discuss.
Thanks :)
