### ISSUE TITLE
How to add "hooks" to speed-type?

### ISSUE THREAD

**Issue by ianyepan** [dakra/speed-type#27]
As titled, I'm an Evil user, and would like to start speed-type in evil-insert-state (i.e. INSERT mode in Vim). Since speed-type does not have its own mode, I couldn't do something like this:

```emacs-lisp
(add-hook 'speed-type-mode-hook #'evil-insert-state)
```
How can I workaround this? Perhaps advice-add upon the `speed-type-text` function?

**Comment by texaco** [comment]
Hi! I have already applied a PR creating a major mode. Here https://github.com/parkouss/speed-type/pull/30

I have successfully attached a hook for olivetti-mode so I think it would work also for you.

Best regards!!

**Comment by dakra** [comment]
#30 is finally merged :)

**Comment by texaco** [comment]
Nice to see some movement here!
