### ISSUE TITLE
Is this project abandoned?

### ISSUE THREAD

**Issue by j0ni** [dakra/speed-type#32]
Hello!

It seems that a bug from 2017 parkouss/speed-type#9 which led me to stop using this package is still open and valid! I see some attempts to fix, but the last comment was in 2017.

Last activity in the repo seems to be several years ago, at least the main branch.

Is this project abandoned?

Thanks.

**Comment by matthew-piziak** [comment]
As far as I can tell there is also no license. I believe that precludes forks.

**Comment by dakra** [comment]
There is no license file or spdx-license identifier but I guess(/hope?) the GPL clause in the code is enough: https://github.com/parkouss/speed-type/blob/master/speed-type.el#L12-L23

**Comment by matthew-piziak** [comment]
@dakra Oh okay, well spotted!

**Comment by dakra** [comment]
@parkouss if you want you can add me as a maintainer to this project and I would look at some PRs and issues when my time allows.

**Comment by dakra** [comment]
I emails @parkouss and unfortunately he's too busy with other stuff to maintain this package any more
but kindly agreed to transfer the repo to me so I can have a look at the issues and outstanding PRs.

**Comment by matthew-piziak** [comment]
Thank you @dakra!!
